SELECT 
II.INGREDIENT_TYPE,
SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM
FIRST_HALF FH
JOIN
ICECREAM_INFO II
ON
FH.FLAVOR = II.FLAVOR
GROUP BY 
II.INGREDIENT_TYPE
ORDER BY
TOTAL_ORDER

-- SELECT
-- SUM(FH.TOTAL_ORDER)
-- FROM
-- FIRST_HALF FH
-- JOIN
-- ICECREAM_INFO II
-- ON
-- FH.FLAVOR = II.FLAVOR
-- WHERE
-- II.INGREDIENT_TYPE = 'fruit_based'